{{- if .Values.keda.enabled }}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {scaled-object-name}
spec:
  scaleTargetRef:
    deploymentName: {deployment-name} 
    containerName: {container-name}                                   
  pollingInterval: {{ .Values.keda.pollingInterval | default "30" }} 
  cooldownPeriod:  {{ .Values.keda.cooldownPeriod | default 300 }}     # Optional. Default: 300 seconds
  minReplicaCount: {{ .Values.keda.minReplicaCount | default "0" }}    # Optional. Default: 0
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default "100" }}  # Optional. Default: 100
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Israel
        start: * * 8 * *
        end: * * 12 * * 
        desiredReplicas: "1"
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
    - type: memory
      metadata:
        type: AvarageValue
        value: "70"
{{ end }}
